In [1]:
import numpy as np 
import torch


In [65]:
torch.manual_seed(42)
np.random.seed(42)

In [66]:
arr = np.random.randint(0,5,(1,6))

In [67]:
arr

array([[3, 4, 2, 4, 4, 1]])

In [68]:
x = torch.tensor(arr)

In [69]:
x.type(torch.int64)

tensor([[3, 4, 2, 4, 4, 1]])

In [70]:
x.dtype

torch.int64

In [71]:
x = x.reshape(3,2)

In [72]:
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [73]:
x[:,1]

tensor([4, 4, 1])

In [74]:
x*x

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [75]:
y = torch.randint_like(x,low=0,high=5).reshape(2,3)

In [76]:
torch.mm(x,y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])