In [2]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.random.rand(1)

array([0.6097596])

In [5]:
np.random.randn(5)

array([-0.52499823, -0.63537272,  0.54666227, -0.77764521, -1.55776911])

In [6]:
np.random.normal(5,6)

-3.416990776209989

In [7]:
np.random.randint(1,100)

19

In [8]:
np.random.randint(1,100,10)

array([23, 81, 55,  7, 49, 19, 91,  2, 94, 90])

In [9]:
np.random.seed(42)

In [11]:
np.random.rand(4)

array([0.79654299, 0.18343479, 0.779691  , 0.59685016])

In [13]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [14]:
arr = np.arange(0,25)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
ranarr = np.random.randint(1, 100,25)

In [17]:
ranarr

array([10, 78, 41,  5, 64, 41, 61, 93, 65,  6, 13, 94, 41, 50, 84,  9, 30,
       60, 35, 45, 73, 20, 11, 77, 96])

In [18]:
ranarr.reshape(5,5)

array([[10, 78, 41,  5, 64],
       [41, 61, 93, 65,  6],
       [13, 94, 41, 50, 84],
       [ 9, 30, 60, 35, 45],
       [73, 20, 11, 77, 96]])

In [19]:
ranarr.max()

np.int64(96)

In [20]:
ranarr.min()

np.int64(5)

In [21]:
ranarr.argmax()

np.int64(24)

In [22]:
ranarr.argmin()

np.int64(3)

In [23]:
ranarr.dtype

dtype('int64')

In [24]:
type(ranarr)

numpy.ndarray