In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

np.int64(0)

In [5]:
arr[8]

np.int64(8)

In [6]:
arr[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
add_arr = arr + 100

In [11]:
add_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [12]:
multi_arr = arr * 100

In [13]:
multi_arr

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy[:] = 1000

In [22]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[4,5,6],[1,9,10],[45, 64,32]])

In [28]:
arr_2d  

array([[ 4,  5,  6],
       [ 1,  9, 10],
       [45, 64, 32]])

In [29]:
arr_2d.shape

(3, 3)

In [30]:
arr_2d[1]

array([ 1,  9, 10])

In [31]:
arr_2d[1][1]

np.int64(9)

In [32]:
arr_2d[1,1]

np.int64(9)

In [33]:
arr_2d[2,2]

np.int64(32)

In [34]:
arr_2d[2,0]

np.int64(45)

In [38]:
arr_2d[:2]

array([[ 4,  5,  6],
       [ 1,  9, 10]])

In [39]:
arr_2d[:2,1:]

array([[ 5,  6],
       [ 9, 10]])

In [40]:
arr = np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
arr > 4 * 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr > 4

In [45]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])