In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.5.1+cpu'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [8]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
x = torch.from_numpy(arr)

In [11]:
x

tensor([1, 2, 3, 4, 5])

In [12]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [13]:
x.dtype

torch.int64

In [14]:
arr2d = np.arange(0.0,12.0).reshape(4,3)

In [15]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
torch_2d = torch.from_numpy(arr2d)

In [17]:
torch_2d.dtype

torch.float64

In [18]:
type(torch_2d)

torch.Tensor

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
arr[0] = 99

In [21]:
arr

array([99,  2,  3,  4,  5])

In [22]:
x

tensor([99,  2,  3,  4,  5])

In [23]:
arr3 = np.arange(0,10)

In [24]:
my_ten = torch.tensor(arr3)

In [25]:
my_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[0] = 99

In [27]:
arr

array([99,  2,  3,  4,  5])

In [28]:
my_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr3[0] = 99

In [30]:
arr3

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [31]:
my_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])