In [1]:
import torch
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
x = torch.tensor(arr)

In [4]:
x2 = torch.Tensor(arr)

In [5]:
x

tensor([1, 2, 3])

In [6]:
x2

tensor([1., 2., 3.])

In [7]:
torch.empty(2,2)

tensor([[2.1715e-18, 2.3081e-12],
        [1.8590e+34, 7.7767e+31]])

In [8]:
 arr2 = np.arange(0,11)

In [9]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
x_1 = torch.from_numpy(arr2)

In [13]:
x_2 = torch.as_tensor(arr2)

In [14]:
x_1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
x_2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
x_3 = torch.tensor(arr2)

In [17]:
arr2[0] = 99

In [18]:
x_1

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
x_3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [24]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [25]:
my_tensor = torch.tensor([1,2,3,4])
my_tensor.dtype
my_tensor.type(torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [26]:
torch.rand(4,3)

tensor([[0.1103, 0.9588, 0.2130],
        [0.5252, 0.9236, 0.1274],
        [0.9317, 0.8365, 0.9555],
        [0.7795, 0.7882, 0.0082]])

In [27]:
torch.randn(4,3)

tensor([[-1.2457, -0.9887,  0.5790],
        [-0.0299,  0.8631, -0.1319],
        [ 1.3476, -1.2766,  0.5080],
        [ 1.2495,  0.5845, -0.1541]])

In [31]:
torch.randint(low=0,high=10,size=(5,2))

tensor([[7, 5],
        [0, 1],
        [9, 5],
        [5, 5],
        [9, 0]])

In [32]:
x = torch.zeros(2,5)
torch.rand_like(x)

tensor([[0.3425, 0.2717, 0.5393, 0.1646, 0.8469],
        [0.8944, 0.6852, 0.7236, 0.1948, 0.5523]])

In [33]:
torch.randn_like(x)

tensor([[ 0.5572,  0.6027, -1.0550,  1.8679, -0.4193],
        [-0.8422,  2.3142,  2.7467,  0.0700,  1.3496]])

In [34]:
torch.randint_like(x, low=0,high=11)

tensor([[8., 5., 1., 5., 6.],
        [7., 4., 2., 3., 2.]])

In [35]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])