In [1]:
import numpy as np
import torch

In [2]:
x = torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
x[1,1]

tensor(3)

In [5]:
x = torch.arange(0,10)

In [6]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array = torch.arange(0,10)

In [14]:
array.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
array.view(-1,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
array2 = torch.arange(0,6)

In [20]:
array3 = torch.arange(7,13)

In [21]:
array2 + array3

tensor([ 7,  9, 11, 13, 15, 17])

In [23]:
array2 * array3

tensor([ 0,  8, 18, 30, 44, 60])

In [26]:
# true matrix multiplication 
array2.mul(array3) # element by element 

tensor([ 0,  8, 18, 30, 44, 60])

In [27]:
array2.dot(array3)

tensor(160)

In [29]:
a = torch.tensor([[0,2,4], [1,3,5]])

In [30]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [31]:
a.shape

torch.Size([2, 3])

In [32]:
b.shape

torch.Size([3, 2])

In [33]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [34]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [37]:
x = torch.tensor([3.,4.,5.,6.])

In [38]:
x.norm()

tensor(9.2736)

In [39]:
x.numel()

4